[project]
name = "davizct"
version = "0.1.0"
description = ""
authors = [{ name = "Miguel Vieira", email = "jose.m.vieira@kcl.ac.uk" }]
requires-python = ">=3.9,<3.11"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "plotly>=5.13.1,<6",
    "jupyterlab>=3.6.2,<4",
    "jupyter-contrib-nbextensions>=0.7.0,<0.8",
    "wordcloud>=1.9.2,<2",
    "ipylab>=0.7.1,<0.8",
    "pyyaml>=6.0.1,<7",
]

[dependency-groups]
dev = [
    "black>=23.1.0,<24",
    "ipython>=8.11.0,<9",
    "zoonyper",
    "jupyterlab-code-formatter>=1.5.3,<2",
    "isort>=5.12.0,<6",
    "jupyterlab-git>=0.41.0,<0.42",
    "jupyterlab-tabnine>=0.0.24,<0.0.25",
]

[tool.uv.sources]
zoonyper = { git = "https://github.com/kingsdigitallab/zoonyper.git", branch = "v0.1.0" }

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.6.0"
tag_format = "$major.$minor.$patch"
